> An exception propagates from method to method, up the call stack, until it's caught. 

        using System;
        public class Test{
            static void Main(){
                Test test = new Test();        
                try{
                    test.method1();
                }catch(NullReferenceException n){
                    Console.WriteLine(n.Message);
                } 
            }    
            public void method1(){
                method2();
            }    
            public void method2(){
                throw new NullReferenceException("empty");
            }
        }
        
        
        output : 
        empty
        
> exception event moving from method2 to method1 , from method1 to main method. finally exception is 
  handled in Main method.
  or else it leads to unhandled exception
